# Generated by Django 2.2.6 on 2019-11-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitlink',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.TextField(default='N/A'),
        ),
    ]
